### ISSUE TITLE
Not catching misspellings in some Markdown areas

### ISSUE THREAD

**Issue by cretz** [bartosz-antosik/vscode-spellright#105]
Some nested bullets don't get checked, e.g.

![image](https://user-images.githubusercontent.com/206396/34373469-d77dc106-eaa0-11e7-95f4-880e7a7b71f8.png)

Notice how the third and fourth there aren't checked. There are probably other places in the markdown file that don't get checked either.

**Comment by bartosz-antosik** [comment]
Hi! No, it probably does not affect other places. It was caused consciously by #100 and I have no idea at the moment how to reasonably judge whether something that is indented by 4 spaces is code block or bullet.

**Comment by cretz** [comment]
Four space indent does introduce a code block when it's not a bullet IIRC. Commonmark makes this clearer. I do not know the exact rules (commonmark may be good to look at here for exact), but a check that the block doesn't start with a bullet might be warranted. Granted, based on [some tests](https://gist.github.com/clintel/1155906) you may not be able to get by with stateless, logic-less regex alone to determine what is and isn't a codeblock (you might have to count what level you are at, at which point if you really want to do it right, you grab an actual markdown parser or you leverage vscode's built in one somehow to access the AST)

**Comment by bartosz-antosik** [comment]
Thanks for the input. I will have to deliberate on this a while.

**Comment by bartosz-antosik** [comment]
I see that this causes problems even to VSCode parser (syntax highlight vs. preview):

![image](https://user-images.githubusercontent.com/20492548/34412581-6718b418-ebde-11e7-92a0-0e2e51cf26d5.png)

**Comment by bartosz-antosik** [comment]
In version 2.1.0 the regular expression is refined to resolve the case reported. It does not resolve the problem generally and there may be some cases (e.g. far level bullet - code - bullet paragraph continuation) which will generate a false positive but it should help. I will close the thread but l leave a note in my TODO file to maybe investigate it deeper. Would love someone to help refine the internal parser because as far as I can tell there is no way to use VSCodes internal parser!
