### ISSUE TITLE
Correction

### ISSUE THREAD

**Issue by wonderkisemt** [bartosz-antosik/vscode-spellright#112]
Is it possible to enable correction similar to Word? By right click or some floating up botton to choose the desirable word.  Thanks.

**Comment by bartosz-antosik** [comment]
Hi! Sadly, I cannot! Not because I cannot but because the interface that VSCode proposes to the extensions. Extension can only provide 'diagnostics' which are then serviced by the mechanism you know (Ctrl+. etc.) Extensions have no access to the context (right click) menu.

More on this can be found e.g. in #97.
