### ISSUE TITLE
How do I add a word to the dictionary?

### ISSUE THREAD

**Issue by joereplicator** [bartosz-antosik/vscode-spellright#116]
That's it. 

I used the word "keto" and it wants to offer all sorts of other words like kilo, etc. 

Keto is short for ketogenic a very popular diet plan these days. 

Thanks, 
Joe

**Comment by bartosz-antosik** [comment]
May I ask - on which platform? Linux, Windows or macOS?

**Comment by bartosz-antosik** [comment]
Normally you use one of these options (`Add "keto" to workspace/user dictionary`):

![image](https://user-images.githubusercontent.com/20492548/36227746-5ecc4db4-11d2-11e8-8391-ed514034621b.png)

You can also set `spellright.addToSystemDictionary` to `true` to have the word added to system (e.g. maintained by Windows Spelling API) custom dictionary, instead of User dictionary.

**Comment by joereplicator** [comment]
THANK YOU!
