### ISSUE TITLE
Deactivate spellcheck in preamble & ignore commands (Latex)

### ISSUE THREAD

**Issue by lbittarello** [bartosz-antosik/vscode-spellright#120]
Thanks for the great package!

I've two questions:

* Is there a way to deactivate spellchecking in the preamble of Latex files?
* How do I deactivate spellchecking for short commands (e.g., `\bfseries`)? I couldn't figure out the proper regular expression to use.

**Comment by bartosz-antosik** [comment]
Hi! Could you help me understand things? 

1) if I understand LaTeX correctly there should be nothing (except comments) to spell in the preamble, because of point 2).
2) Anything that looks like LaTeX markup should already be removed from spelling, so there should be no need to remove things like `\bfseries`.

Like here:

![image](https://user-images.githubusercontent.com/20492548/36803294-70775fc8-1cb7-11e8-8bcc-1a270fa4b4d4.png)

**Comment by lbittarello** [comment]
I get hints for magic comments (e.g., `lualatex` is underlined in `% !TEX program = lualatex`) and some package options (e.g., `labelfont` and `footnotesize`  are underlines in `\captionsetup[figure]{font = {footnotesize}, labelfont = {footnotesize}, skip = 2ex}`).

I only get hints for `\bfseries` within certain commands, such as `\title{}` and `\footnote`. You're right that I don't get hints in the main text.

**Comment by bartosz-antosik** [comment]
Your generalization was misleading to me hence the questions. Things you mention seem to be actually three separate things but the observations were great! They should be all addressed in latest update (2.1.24).

Shall you have more observations about LaTeX please report them! Thank you.
