### ISSUE TITLE
Spellchecking parenthetical plurals in LaTeX documents

### ISSUE THREAD

**Issue by philipstarkey** [bartosz-antosik/vscode-spellright#135]
If you write a parenthetical plural in a LaTeX document (such as `process(es)`), spellright treats the `es` as an independent word. I would suggest that, for LaTeX anyway, parenthetical plurals are spellchecked as a single word without the parentheses (ideally, it would check both `process` and `processes` in the above example.)

**Comment by bartosz-antosik** [comment]
Hi, it is somehow done in version 2.2.10. I have given it quite a thought but it turns out doing this entirely is beyond this extension. In English it maybe could be possible to spell both the core and core plus the suffix and decide which part is correct which not. But parenthetical plurals work in other languages where the suffix is not additive part of the core word. It would require some flexion involved to get correct form...

So for now the decision is to detect such a words and avoid spelling of the part in parenthesis to avoid false positive.
