### ISSUE TITLE
Inconsistent language identifiers across different OSs

### ISSUE THREAD

**Issue by xupefei** [bartosz-antosik/vscode-spellright#136]
Hello, when I was working on my Mac and Windows PC, I found that their language identifier is different: macOS uses `_` whereas Windows uses `-`. For example:
* macOS: `"spellright.language": "en_GB"`
* Windows: `"spellright.language": "en-GB",`

This cause a modification of `settings.json` every time when switching between these OSs. Could you fix this? One simple solution could be keeping the configuration as-is and replacing the `_`/`-` character every time when reading it.

**Comment by bartosz-antosik** [comment]
The fact is that I have not interpreted this field in any of the OSes. It's quite reasonable as when working with Hunspell (Linux and e.g. Windows 7) the names of the dictionaries can be formed freely (e.g. `English (American)`). I will see what can be done, because I am not sure if I have a certain way to know who supports which standard, e.g. who supports ISO (the dash `-`).

**Comment by bartosz-antosik** [comment]
This should be extended in the new version, where `_` & `-` should be effectively treated same way.
