### ISSUE TITLE
Mispelling flagged within Markdown link.

### ISSUE THREAD

**Issue by cfjedimaster** [bartosz-antosik/vscode-spellright#142]
Consider this code block:

```
In addition to the web-based editor, Extend platform comes with a lower level command line tool called [wt-cli](./wt-cli).
```

I had previously added "wt-cli" to the dictionary and it correctly removed it from the list of misspelled words in the dictionary. However, it is still showing red and underline in the link portion (the parenthesis).

![image](https://user-images.githubusercontent.com/393660/38834729-e6a1ffd6-418e-11e8-9347-02e8cbd2e803.png)

**Comment by bartosz-antosik** [comment]
Could you please show me context menu that appears for the squiggle? 

Because I cannot reproduce the error. I have also checked that Markdown parser ignores everything in round braces behind link label as it is supposed to do so it simply does not check this area.

![image](https://user-images.githubusercontent.com/20492548/38853812-bb2c9f92-421e-11e8-903e-caf613e54234.png)

**Comment by bartosz-antosik** [comment]
Could you please check whether this is not a "Plain Text" document class? Because I really cannot reproduce this on Markdown document but it does act like this on plain Text one.

And yes, it should not act like this on Plain Text document either.

**Comment by cfjedimaster** [comment]
I can confirm it is a Markdown file.

**Comment by bartosz-antosik** [comment]
Could you please tell me what OS/version is this?

**Comment by cfjedimaster** [comment]
Windows 10, very latest Code Insiders build.

**Comment by cfjedimaster** [comment]
So I'm on another machine (laptop) and I'm unable to replicate this. However, in the same file, I'm clearly seeing spelling errors for links:

![image](https://user-images.githubusercontent.com/393660/39013233-c55711a6-43e4-11e8-8c45-1df627bb8ea1.png)

You can see it in the second to last link. This is the same file as the original report.

**Comment by cfjedimaster** [comment]
Ahah! If I change the link to http://www.cnn.com/api/http-api, it no longer flags as an error. So for some reason, the relative link is not properly being ignored.

**Comment by bartosz-antosik** [comment]
I am sorry but there is still something not right. What you have shown does not reproduce. Here is snapshot in `Markdown`:

![image](https://user-images.githubusercontent.com/20492548/39014919-03584f38-441c-11e8-8630-cbb0b10c9483.png)

However if I change the type of the document to `PlainText` then I get simillar results to what you have:

![image](https://user-images.githubusercontent.com/20492548/39014888-e31a0d2e-441b-11e8-80c1-abad63f8f170.png)

And it is perfectly justified, because plain text does not not eliminate Markdown type links (`[]()`) BUT it does skip spelling URLs (and e-mail addresses).

Conclusion is that there is something missing in your description of the problem. 

Are you sure this is Markdown type recognized by the Spell Right (it recognizes few markdowns like markdown, R Markdown, madoko, asciidoc etc. but there are other, implemented by extensions, which it will not recognize on it's own)? Instead it will ask you to choose a generic parser for the type - maybe you have chosen/set a parser different parser for this type of document? Do you have anything set in `spellright.parserByClass` config setting?

Could you please provide a small document which sells incorrectly in all of your systems and post it here so that I can reference check it?

**Comment by cfjedimaster** [comment]
It was definitely markdown. It said as such in the lower right corner. I could view the preview too. I switched to plain text, then back to markdown, and they went away. So I'm blaming VSC for this. I say just close it and sorry for the trouble. :)

**Comment by bartosz-antosik** [comment]
No, it's not a trouble at all. But I would be happy to nail this.

**Comment by bartosz-antosik** [comment]
It's Insiders version, so who knows. Maybe. Thanks.

**Comment by borekb** [comment]
I also encountered this today:

<img width="419" alt="screenshot 2018-11-07 at 09 28 39" src="https://user-images.githubusercontent.com/101152/48119495-b6beb980-e26f-11e8-99d9-ed61fcd2400c.png">

In fact, it is strange because there are three similar links in a paragraph and only two are marked as misspelled:

<img width="1009" alt="screenshot 2018-11-07 at 09 30 43" src="https://user-images.githubusercontent.com/101152/48119565-dce45980-e26f-11e8-8972-2ec4c146467f.png">
