### ISSUE TITLE
Spell check code (PHP, JS, HTML)

### ISSUE THREAD

**Issue by alanaasmaa** [bartosz-antosik/vscode-spellright#146]
Can this check code ?

For example css, html classes and id's.

PHP and javascript function names and variables and etc..

I did not found a setting for that
I used https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker and i moved to this becose it supports more languages (Finnish, Estonian, English)

Offtopic: 
Is it possible to set multible languages as default ? For exapmle i have HTML where text is Finnish but comments english.

**Comment by bartosz-antosik** [comment]
Hi! The answer to first question is no, this is intentional. This speller for all documents considered code spells comments/strings. I think this is a job for appropriate linter to check code correctness, and appropriate linters do this much more effectively as spell check is (in my opinion) not a way to spell code keywords.

It does spell CamelCase, snake_case, split2digit etc. splitting the compound words accordingly, but only for the parts of documents it spells (depending on document type, see README for details).

Yes, you can select different language for different syntactic elements of the document (e.g. Finnish for strings, English for comments) using `spellright.languageContext` and `spellright.languageContextByClass`. Also please have a look to the README for details.

**Comment by alanaasmaa** [comment]
The reply was fast, thank you. 

Actually i think its fine if it wont check code. I can write the variable into comments first to spellcheck it. 

spellright.languageContext is not right setting for me cause some projects its all english. 

But i think you reply was still awesome.

**Comment by bartosz-antosik** [comment]
Thank you.

Also, you can set the `spellright.languageContext` in workspace (folder) settings or even you can have it set "per root" (multi-root workspace concept - refer to VSCode) so you can have comments/strings spelled in different languages only  for particular project (or document class using `spellright.languageContextByClass`).
