### ISSUE TITLE
How to check Asciidoc files by default

### ISSUE THREAD

**Issue by blueray453** [bartosz-antosik/vscode-spellright#156]
It shows that the files supported by default are

`spellright.documentTypes: [ "plaintext", "markdown", "latex" ]`

I want to add `.adoc` file here.

How can I do that?

**Comment by bartosz-antosik** [comment]
This does not show that these document types are supported but they are spelled by default. Many more document types are supported. And you do not add there an extension type but document class (because you can have multiple extensions for particular document type).

There are two ways to proceed:

1. Simply switch language in status bar from `[off]` to some language while have the asciidoc document open. See here:

![screenshot-switch-off](https://user-images.githubusercontent.com/20492548/39958146-16584396-55ff-11e8-89f1-d130775c1ca9.png)

![screenshot-switch-on](https://user-images.githubusercontent.com/20492548/39958147-1b538ff4-55ff-11e8-851e-5e6a3574e277.png)

2. Add 'asciidoc' to the setting you mention (if the extension that you use for ASCIIDoc uses this document class name. You can check it by clicking on the document type selector in status bar - there where is written `LaTeX` on the screenshots above):

`spellright.documentTypes: [ "plaintext", "markdown", "latex", "asciidoc" ]`
