### ISSUE TITLE
Feature request: exclude files using filename pattern

### ISSUE THREAD

**Issue by neilsustc** [bartosz-antosik/vscode-spellright#16]
For example, `.gitignore`

**Comment by bartosz-antosik** [comment]
It's .spellignore! See README.md for details.

**Comment by neilsustc** [comment]
Cool!

A global setting would be better. I mean moving `.spellignore` into vscode `settings.json`. Creating `.spellignore` per workspace is kind of inconvenient.

I mentioned `.gitignore` *just* because I want to exclude it 😂.

**Comment by bartosz-antosik** [comment]
I think I have understood it correctly, that you need to exclude .gitignore.

I was thinking that 1) gitignore has some solid rules and is well known, should be mimicked. 2) It should absolutely be workspace because of relative paths that can (are) often used 3) It's pretty dangerous mechanism - you can wonder for hours why "It does not spell my file(s)" forgetting some global setting you made long ago. Hence workspace. And hence red light in Status Bar when file is excluded by this mechanism.

**Comment by neilsustc** [comment]
😮, quite thoughtful

And how can I ignore `.gitignore` globally?

**Comment by bartosz-antosik** [comment]
That is a good question! Let me meditate on this for a second!

**Comment by bartosz-antosik** [comment]
Please have a look at `ignoreFiles` global setting in version 1.0.18. Should do what you need. BTW it disables `.gitignore` and `.spellignore` files by default.
