### ISSUE TITLE
"Add X to workspace directory" adds to folder, not workspace

### ISSUE THREAD

**Issue by GandalfSaxe** [bartosz-antosik/vscode-spellright#189]
If I choose `Add X to workspace directory` on any unknown word word, it adds it to the FOLDER `.vscode/spellright.dict`, not to the workspace settings.

I'd suggest either:
1.  adding it into the `.code-workspace`
2. putting a `spellright.dict` file alongside code-workspace file.
3. change name of the context menu item to `Add X to folder directory` or something like that.

As it stands right now that context menu option actually lies :)

**Comment by bartosz-antosik** [comment]
First: It's "Add X to workspace dictionary", not directory.

Second: I would politely disagree. `.vscode` directory exists only if there is a root folder of the workspace. There can be many root folders from some time (`multiroot workspace`). So there can be multiple `.vscode`s directories each used in specific context (e.g. for different language branch etc.) So `.vscode` is workspace's directory. And I would prefer not to add to `.code-workspace` (which would be BTW adding to the workspace, not workspace directory) because I feel that dictionary is something different than settings - dictionary files are easier e.g. to copy or compare using a diff tool, etc...

**Comment by GandalfSaxe** [comment]
> First: It's "Add X to workspace dictionary", not directory.

Ah yes, my bad.

> Second: I would politely disagree. .vscode directory exists only if there is a root folder of the workspace. There can be many root folders from some time (multiroot workspace). So there can be multiple .vscodes directories each used in specific context (e.g. for different language branch etc.) So .vscode is workspace's directory. And I would prefer not to add to .code-workspace (which would be BTW adding to the workspace, not workspace directory) because I feel that dictionary is something different than settings - dictionary files are easier e.g. to copy or compare using a diff tool, etc...

On second thought, I completely agree with you. Thank you for elaborating.

**Comment by bartosz-antosik** [comment]
Thanks.
