### ISSUE TITLE
Disable the files highlight in red in the side bar

### ISSUE THREAD

**Issue by mvaneijgen** [bartosz-antosik/vscode-spellright#191]
I have some spelling errors in my files which are fine and I don't want to go through them and mark them all as ignore, but now my `Active file side bar` looks like a scene from a Quentin Tarantino movie.

What is the option to disable the highlight in the sidebar

![Inglourious vscode](https://i.imgur.com/6wFE9A8.jpg)

**Comment by bartosz-antosik** [comment]
I am afraid it is not me who does this! Besides I know very little about Tarantino movies but I suppose they very red!

One can do very little in this aspect in VSCode. Extension prepares 'diagnostics' and all the displaying about them is done by VSCode. You may however try to see what happens when you change "spellright.notificationClass" to different values - I have not done this so I do not know.

**Comment by TechAurelian** [comment]
I can confirm that after setting `spellright.notificationClass` to `information` for example, I only get a blue highlight under the misspelled word in the editor, and no more red file names in the VSCode Explorer.

![image](https://github.com/bartosz-antosik/vscode-spellright/assets/108275944/ce3cf525-ca05-4428-bbae-14efd8148799)

I'm using Visual Studio Code version 1.81.1 on Windows 11, with Spell Right version 3.0.116.
