### ISSUE TITLE
Remove errors from "Problems" panel

### ISSUE THREAD

**Issue by sillyfrog** [bartosz-antosik/vscode-spellright#200]
I'm just getting into VS Code, so this maybe more an issue on that side.

I have installed Spell Right, and it's doing what it should, but I can't figure out how to remove all of the entries in the "Problems" panel. I have tried setting the "Notification Class" to various levels (I have ended up on "Information"), the problem with hint is I can't easily see if a word has a problem.

Ideally I would like to have the misspelled words underlined, but _not_ show up in the "Problems" panel.

It maybe I'm using the wrong terminology when searching, but it feels like something others would also want.

Thanks for making such a great plugin!

**Comment by bartosz-antosik** [comment]
Thank you for appreciation!

Sadly the so called "diagnostics" is the only thing that the extension is supposed to produce to make marks in the document. So straight answer is no, you cannot have underlines without diagnostics in diagnostics panel and this is "by design" and requests for change of this state should be posted on VSCode's issues list. And yes, you use the terminology quite correctly.

**Comment by justin-irl** [comment]
Bumping this rather than opening a new issue, would it be possible to consider something like this?

`spellright.diagnosticLevel": "Hint",`

Sources:
- https://stackoverflow.com/questions/50309834/vs-code-enable-inline-spell-checker-but-disable-spell-check-in-the-problems
- https://github.com/microsoft/vscode/issues/44141
- https://github.com/microsoft/vscode/issues/95707

![image](https://user-images.githubusercontent.com/22618333/161188981-ccc7dd90-4068-4f24-a87f-d0afd7a75f61.png)
