### ISSUE TITLE
enable spellright for all document types?

### ISSUE THREAD

**Issue by svenevs** [bartosz-antosik/vscode-spellright#210]
It's unclear to me if there is an easier way to do this.  Ideally I think it would be nice to have

```json
"spellright.documentTypes": "all", // string exactly 'all' means all files
// or the explicit way
"spellright.documentTypes": ["lang1", "lang2", "langN"]
```

I could have overlooked it, but it seems I need to specify them all manually.  I harvested these language types from [vscode identifiers docs](https://code.visualstudio.com/docs/languages/identifiers):

```json
  // condensed version
  "spellright.documentTypes": [
    "abap", "bat", "bibtex", "clojure", "coffeescript", "c", "cpp", "csharp",
    "css", "diff", "dockerfile", "fsharp", "git-commit", "git-rebase", "go",
    "groovy", "handlebars", "html", "ini", "java", "javascript", "json",
    "jsonc", "latex", "less", "lua", "makefile", "markdown", "objective-c",
    "objective-cpp", "perl", "perl6", "php", "powershell", "jade", "python",
    "r", "razor", "ruby", "rust", "scss", "sass", "shaderlab", "shellscript",
    "sql", "swift", "typescript", "typescriptreact", "tex", "vb", "xml", "xsl",
    "yaml"
  ]
```

or

```json
  // easily 'commentable' version
  "spellright.documentTypes": [
    "abap",
    "bat",
    "bibtex",
    "clojure",
    "coffeescript",
    "c",
    "cpp",
    "csharp",
    "css",
    "diff",
    "dockerfile",
    "fsharp",
    "git-commit",
    "git-rebase",
    "go",
    "groovy",
    "handlebars",
    "html",
    "ini",
    "java",
    "javascript",
    "json",
    "jsonc",
    "latex",
    "less",
    "lua",
    "makefile",
    "markdown",
    "objective-c",
    "objective-cpp",
    "perl",
    "perl6",
    "php",
    "powershell",
    "jade",
    "python",
    "r",
    "razor",
    "ruby",
    "rust",
    "scss",
    "sass",
    "shaderlab",
    "shellscript",
    "sql",
    "swift",
    "typescript",
    "typescriptreact",
    "tex",
    "vb",
    "xml",
    "xsl",
    "yaml"
  ]
```

If this feature does not exist, would you like a docs PR to add either the `condensed` or the `easily 'commentable'` version as an example?  It wasn't super hard to create, but nice to have in the docs for convenient copy-pasting for users :slightly_smiling_face:

Thanks for the extension I like it!

**Comment by bartosz-antosik** [comment]
Hi! I am afraid that it was designed quite other way. Spell Right has 5 parsers which are used to extract parts of document's to spell (like `code` parser which aims to extract strings and comments). So assigning `all` types to spell has very little sense because Spell Right would not know which type of parser to apply. 

Thus for some time now once you open unknown type of document Spell Right pops a list of parsers to choose from and then registers the choice in settings automatically (there was recently an issue #205 preventing the mechanism from registering the settings but the resolution will be published very soon):

![image](https://user-images.githubusercontent.com/20492548/45807956-e9fbb800-bcc4-11e8-9e2b-45734c244989.png)

It is all described in the documentation.

But you may be right in this aspect that Spell Right knows less document types than there are in bare (I mean without extensions) VSCode. It may have changed from the time when Spell Right was created. I will check this. Was this the point of your inquiry?

**Comment by svenevs** [comment]
Hmm.  I think that answers my question, though it possibly raises others ;)  I'll re-read the docs since I clearly missed this point...
