### ISSUE TITLE
Full CPU load in Ubuntu 17.04

### ISSUE THREAD

**Issue by pjssilva** [bartosz-antosik/vscode-spellright#51]
Hi,

Thanks for the work. I looks very promising. I am using the extension in Ubuntu 17.04. It feels very slow and the extension seems to trigger very large CPU load. The process causing it is

/usr/share/code/code /usr/share/code/resources/app/out/bootstrap --type=extensionHost

**Comment by bartosz-antosik** [comment]
Could you please try to set: `suggestionsInHints` to false and see if it is still slow & loads CPU to 100%?

**Comment by pjssilva** [comment]
It does not make any difference.

**Comment by bartosz-antosik** [comment]
Is the load constant? E.g. when you stop typing does it go down towards 0 or it stays on saturated core? Or is it that once you e.g. switch tabs to a larger document goes 100% and after some time goes down?

Could you maybe elaborate a bit more on "It feels very slow"? In what sense - large documents take a lot of time to spell or is it any other sense of slowness?

**Comment by pjssilva** [comment]
Sorry for the delay in the feedback. 

The test is very simple. Open Code without any file. Create a new tab with Ctrl-N and start typing making a few errors on purpose. After the first line the errors take long to be marked (they are marked many seconds after the word was typed), the CPU usage of a core jumps to 100%. After you stop typing with only three lines the CPU remains at 100% for many seconds, let's say 30s. When the CPU usage goes down all the incorrect word are marked.

I am using a Portuguese - Brazilian dictionary from 

https://github.com/titoBouzout/Dictionaries

Those dictionaries works in Sublimetext, for example.

**Comment by bartosz-antosik** [comment]
Could you please do a same test with other spelling dictionary, e.g. English (American), of the same source?

**Comment by bartosz-antosik** [comment]
A moment ago published version 1.1.22 should resolve the problem shall my investigation been correct.

I suppose that the problem was setting the dictionary multiple times with Hunspell (backend for spelling on Linux). Unlike other engines Hunspell each time loads dictionary/affixes files which takes a lot of time and CPU. It should be better now when the dictionary should not be reloaded unless the language spelled changes. 

Please let me know if the diagnosis was correct!

**Comment by pjssilva** [comment]
Yes! It works well enough! Thanks. This is a major contribution for the code editor. I can not understand how an editor can reach with 1.0 without a good, builtin, multi-language spell checker. It seems like you have the first good one. Great work!

**Comment by bartosz-antosik** [comment]
Thank you, this is a great news!

I had the same considerations some ago. They are described in more details, by me, in [#20266](https://github.com/Microsoft/vscode/issues/20266).  ;-)

Your situation is healed well but for one language. It will backfire however if it would happen you have a multi-language document (more than one language in one document). It would be a pain again as Hunspell takes quite some time to load dictionary & it does not cache prepped dictionary as other backends do. But I will try to keep this in mind and do some cache internally.

Aside speaking: I thought Polish language has large affixes system (which also described [#20266](https://github.com/Microsoft/vscode/issues/20266)) due to a developed flexion system and a lot of exceptions. But it seems it is nothing compared to Portuguese which has affixes file three times as big! This is what takes time & CPU to load. In case of e.g. English it is barely perceptible!

**Comment by pjssilva** [comment]
Funny language, isn't it? I have been suffering with this large load times for a while. Specially if the implementation insists on loading the full dictionary in memory first (generating all possible words). But your code does not seem to do that, as it starts fast at least when I have only Portuguese as language.

Thanks again.

**Comment by bartosz-antosik** [comment]
I would say quite developed language!
