### ISSUE TITLE
Spell checking with camel case

### ISSUE THREAD

**Issue by borekb** [bartosz-antosik/vscode-spellright#54]
I've already reported something similar in #26 but Spell Right changed the behavior since then so this is a new one. Basically, I have this spell checking error:

![image](https://user-images.githubusercontent.com/101152/29633475-af01b2c6-8846-11e7-8c6a-3c75d904c4f3.png)

I would like to add the word "PhpStorm" to my system dictionary (I use `"spellright.addToSystemDictionary": true`) but don't know if it's possible. If I press `Ctrl + .`, I get these suggestions:

![image](https://user-images.githubusercontent.com/101152/29633603-248089c8-8847-11e7-87e7-902843235a4a.png)

I don't really want to add "Php" to my dictionary, that is a spelling error on its own. Ideally, Spell Right should treat PhpStorm as a single word (which it is).

**Comment by bartosz-antosik** [comment]
You may have missed it, but please have a look at #43. Once you add `PhpStorm` to any of the user dictionaries it will be spelled correctly as the whole word.

**Comment by bartosz-antosik** [comment]
The whole mechanism of matching compound first then split parts has been present for some time. If only you had `PhpStorm` in any of the dictionaries it would get spelled correctly. I think it was you, who have provoked this some ago - maybe because of something it went unnoticed.

**Comment by borekb** [comment]
_Add Selection to User Dictionary_ is exactly what I wanted! I'm thinking whether the discoverability of this command can be improved somehow, by adding it to the `Ctrl+.` menu, but have no good ideas I'm afraid. Thanks.

**Comment by bartosz-antosik** [comment]
It is not possible to add "Add Selection to (...)" to the diagnostics menu! Because it does not show contextually over ANY things but only over things that HAVE diagnostics message.

There could be option as suggested in #43 but I was skeptical about it and I decided not to clutter the menu. I will reiterate on this maybe but I generally think the whole idea of having spelling as "diagnostics" is IMHO a bad idea yet there is no other possibility at the moment. There is even no possibility of having a separator between suggestions & options, which would made it much more clear. Generally there should be access to context menu (right click on anything) then a sub-menu could hide more advanced options like what we are talking about.

**Comment by borekb** [comment]
Strange, right after I do _Add Selection to User Dictionary_, the word "PhpStorm" is spell-checked correctly. However, after I restart VSCode, the red squiggly is back:

![image](https://user-images.githubusercontent.com/101152/30252937-6217e9e2-967b-11e7-8dc0-24f02c04771e.png)

The word is clearly in my dictionary (I use `"spellright.addToSystemDictionary": true`, this is from file `C:\Users\borek\AppData\Roaming\Microsoft\Spelling\en-US\default.dic`):

![image](https://user-images.githubusercontent.com/101152/30252934-5bd45728-967b-11e7-9862-e68e7998f08c.png)

**Comment by bartosz-antosik** [comment]
Quite strange. I will have a look.

**Comment by bartosz-antosik** [comment]
This is an error. It is corrected (I hope) now. Could you please rise this to a regular issue?

**Comment by bartosz-antosik** [comment]
Never mind. I already did in #66.
