### ISSUE TITLE
User dictionary file does not exist

### ISSUE THREAD

**Issue by tyler36** [bartosz-antosik/vscode-spellright#540]
Thank you for the extention. 

While using it, I can add words to the user dictionary, and the swiggles disappear.
However, recently I accidently added an incorrect word. I tried to run the "Spellright: Open User dictionary file" but got the following error:

"SpellRight: User dictionary file does not exist. It will be created when first word is added."

The documentation say the file should be "located in user settings folder", but doesn't go into details. 
Is this `%appdata%\Code\User`? If so, it is indeed "missing".

The question then is, where was the incorrect word added?

VScode: `1.74.1`
Spellright: `v3.0.104`
OS: Win10

**Comment by Arxareon** [comment]
Any updates or extra info on this? I'm trying to use a user-wide dictionary instead of having to copy it between specific workspaces but no such file exists - or I don't know where to look for it. Also, there isn't always an add to dictionary button either so I often have to add words to the dictionary manually. If there is no such file, I'd have to create it manually but I don't know where.

**Comment by tyler36** [comment]
Closing due to lack of response.
