### ISSUE TITLE
Only a limited number of spelling errors can be identified

### ISSUE THREAD

**Issue by Eldaw** [bartosz-antosik/vscode-spellright#55]
It seems there is a limit to the number of spelling errors that can be identified in a text document. I pasted dummy text into a new text file and then turned on Spell Right. After a certain point in the document, no more errors were underlined in red. See the attached screenshot.

![spelling_limit](https://user-images.githubusercontent.com/3789849/29668405-fe04d51a-88d7-11e7-8c81-247e1eb5dbcc.png)

**Comment by bartosz-antosik** [comment]
Yes, there can be a maximum of 250 diagnostic messages is allowed. This is VSCode's limitation. The mechanism to which spelling is connected in various extensions, the "diagnostics" reporting is not the best thing possible (you can e.g. read about it towards the end of README file, in *Known issues* section) at all but there is no other at the moment...

The problem you describe was reflected in #2.

**Comment by Eldaw** [comment]
Would you consider logging it as an issue with the vscode project itself? Or are they already aware and unwilling to change this limitation?

**Comment by bartosz-antosik** [comment]
To say the truth I have not done any research around it. I suppose it's due to performance issues why they limit the number. Also there is some reason in thinking that if there are so many errors probably something is wrong (e.g. spelling language...) Last thing is that when you correct some of these the rest will show...
