### ISSUE TITLE
Comment in user config

### ISSUE THREAD

**Issue by futagoza** [bartosz-antosik/vscode-spellright#60]
I needed to manually change a setting for something else, but when I opened the User settings file, for a split second I thought I had opened the wrong file, because of this comment:
```js
//
// Spell Right global configuration file.
//
```

Wondering why this was there, and thinking there's no need for an extension to add something like that to a user's configuration file, I dug through your code, but the nearest to this I could find was the function at [src/spellright.js#L1466](https://github.com/bartosz-antosik/vscode-spellright/blob/master/src/spellright.js#L1466) that does nearly the identical only for workspace configuration files.

Is there a reason for this? It doesn't block me from doing anything, but it doesn't feel right opening the configuration file and noticing the comment at the top, especially when the only setting to do with Spell Right in that file is the language setting (`"spellright.language": "en-GB"`).

**Comment by bartosz-antosik** [comment]
1. Explanation: I think If I remember correctly, there was "global" for some time, it was clearly an error. I have changed it a while ago, because you have created the file earlier it has preserved the old form.

2. You are right! I had bits of legacy code which did that and I have tolerated this for quite some time, which does not lighten my guilt even a bit! It will be removed in next release.

**Comment by futagoza** [comment]
Sorry for the guilt trip there m8 😆, was up all night on that day debugging a problem, and seeing that there at the top if the configuration file pissed me off, but hey, I tried to be polite in my half pissed/half asleep state 😉

**Comment by bartosz-antosik** [comment]
Absolutely no problem. Maybe I have not realized your offloading your being piss off on me, because I know more places where configuration files do not meet standards, take for example #39, which is essentially, that VSCode ignores errors in User configuration settings...

And from the version that will be published today on, once you call `SpellRight: Create/Update Workspace Settings` it will write a pure JSON without comments. ;-)

Of course if you like Spell Checker you can write a Review to help you cope! ;-)
