### ISSUE TITLE
Latex: doesnt check spell inside brackets of \captionof{table}{ ...here....}

### ISSUE THREAD

**Issue by pycckuu** [bartosz-antosik/vscode-spellright#84]
Great extension!

For some reason it doesnt chech the spell inside the brackets of latex keywords, such as \captionof{table}{ ...here....} on macos. Is there any way to enable it?

**Comment by bartosz-antosik** [comment]
Thank you!

Could you maybe help me with this?

Extension uses a very simple approach with latex parser which uses regular expressions to 'space out' parts of the document that should not be spelled (e.g. latex commands & math blocks). It cannot be rather done using any "latex to text" converted because it has to match the location in the original document. Hence the spacing out process. The expression to select command looks like this:

/\\\w+(\[.*?\])*((\{|\().*?(\}|\)))*(\[.*?\])*/g

You can try it e.g. [here](https://regex101.com/).

Could you maybe help and adjust it so that it select commands or parts that should not be spelled and not select the { ...here....} parts?

**Comment by bartosz-antosik** [comment]
The parts in curly braces are LaTeX parameters. There is virtually no way (other than be a LaTeX compiler) to know which parameters should be spelled (e.g. section headings). Some of them contain symbols which would certainly lead to false positives. So there seems not to be a reasonable way to decide whether to spell them all or not spell them at all (current solution).

I will leave it as it is for now and maybe revert to this issue when I will find a better solution.

**Comment by bartosz-antosik** [comment]
I have just published version 2.0.6 which has a new setting `spellright.latexSpellParameters`. It points LaTeX commands which should have the parameters spelled. By default it is set to spell these: `\title`, `\author`, `\date`, `\section` but of course `\captionof` can be added e.g. in workspace settings (but please remember that it would override not add to the default so you would have to repeat the default commands).

I have not added `\captionof` intentionally because I am not sure what should the best default set be. If you have some suggestions please let me know.

It should be a kind of a solution to the problem introduced by this thread some ago. Please let me know if you agree.
