### ISSUE TITLE
"bulb" directly with word instead of line?

### ISSUE THREAD

**Issue by janpio** [bartosz-antosik/vscode-spellright#91]
It took me a few seconds to realize the "lightbulb" button at the beginning of the line is to be used to see suggestions or add the unknown word to the dictionaries.

Is there a way to place this button directly at the underlined word instead of at the beginning of the line?

**Comment by bartosz-antosik** [comment]
Sadly this is VSCode's feature! Extensions (not only spell right) provide only a structure called "diagnostics" for which framework (bulb, Ctrl+. mechanism etc.) is provided by VSCode. Bulb's location is part of the mechanism and as far as I know there is no way to change it's position.

I have expressed it number of times here and there that the whole mechanism does not fit usage habits for spelling interface but it is not a top priority task and maybe it really is.

P.S. Aforementioned `Ctrl+.` seems better option to correct spelling errors. At least for me.

**Comment by janpio** [comment]
Is there a VSCode issue one could +1 to "vote" for this? This would really improve your extension a lot.

**Comment by bartosz-antosik** [comment]
Sadly, don't know! I know the position of the bulb has changed some ago, but I have not investigated why and hardly noticed when. That would call for searching VSCode's issues. I honestly think there should be a way to add spelling information to right-click context menu rather than to the diagnostics structures. 

Quick search has not revealed anything related to this. As I have rather failed with the issue I have risen some ago [#20266](https://github.com/Microsoft/vscode/issues/20266) i will rather not be eager to start another thread about it as spelling seems not to gain much traction.
