### ISSUE TITLE
Adding to workspace dictionary doesn't seem to do anything

### ISSUE THREAD

**Issue by tasgoon** [bartosz-antosik/vscode-spellright#99]
Whenever I add click on 'Add "\<word\>" to workspace dictionary', the word still gets marked as incorrect. However, adding to the user dictionary has the correct effect.

Am I missing something here?

**Comment by bartosz-antosik** [comment]
Hi! I am tempted to say: Strange, it works for me! ;-)

But of course there may be something I am missing (see questions below).

1) 

![image](https://user-images.githubusercontent.com/20492548/33651480-41940ec4-da66-11e7-851d-68cad71e6b27.png)

2)

![image](https://user-images.githubusercontent.com/20492548/33651513-6745f34e-da66-11e7-87bc-59229edc1ba7.png)

Could you please check:
1) Is `spellright.dict` present in your workspace's `.vscode` folcer?
2) Has the word been added there?

**Comment by el2iot2** [comment]
I hit this as well, but figured it out. The problem was that, while i had saved a `myproject.code-workspace` for my project, i hadn't yet caused a `.vscode` folder to be created. When I customized the "workspace settings" (`ctrl+p`,`>`,`open workspace settings`), suddenly i had a `.vscode` folder and the "add to workspace dictionary" command worked as advertised. I would assume that if you manually added an appropriate `.vscode` folder, you could get this working as well.

There are probably other, better/quicker ways to create the `.vscode` folder for a new project, but 
`ctrl+p`,`>`,`open workspace settings` worked for me. I also had to pull down "Workspace Settings" from the settings combo before the `.vscode` folder (and internal settings file) were created:
![image](https://user-images.githubusercontent.com/28941195/33799143-5e53c6e6-dcda-11e7-9e19-f12d4ef2e9e1.png)

**Comment by bartosz-antosik** [comment]
@el2iot2 Thanks for the input! I will have to think on this - maybe I should 1) disable this option 2) create .vscode folder on my own?

**Comment by el2iot2** [comment]
2 seems reasonable to me if you ask permission to add the .vscode folder in a modal?

Could also toast a message: "cannot add word to workspace dictionary because there is not yet a .vscode folder for this project"?

**Comment by el2iot2** [comment]
As a side note, I have tried a bunch of spell checker plugins, and this is the first that has been reliable and perfomant (and offline) for long markdown files. It works intuitively and well. Thank you for all the effort and work in this space.

**Comment by bartosz-antosik** [comment]
Just published version 2.0.15 should fix this. Bu creating the `.vscode` folder if necessary. I have made a look around and I reckon some extensions create the folder if it does not exist. So it seems legit!

Thanks for kind words in the post above! Maybe you would like to create a [review](https://marketplace.visualstudio.com/items?itemName=ban.spellright#review-details) in the market? ;-)

**Comment by tasgoon** [comment]
Thanks a bunch for all the hard work you've put into this project.
